//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Ninja.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class NinjaLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		FUN_KEYWORD=1, MEANINGFUL_TYPE=2, VOID=3, COMMA=4, OBRACE=5, CBRACE=6, 
		OBRACKET=7, CBRACKET=8, WS=9, INT=10, WORD=11, DOUBLE=12, CALL=13;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"FUN_KEYWORD", "MEANINGFUL_TYPE", "VOID", "COMMA", "OBRACE", "CBRACE", 
		"OBRACKET", "CBRACKET", "WS", "INT", "DIGIT", "WORD", "DOUBLE", "CALL"
	};


	public NinjaLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public NinjaLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'fun'", null, "'void'", "','", "'{'", "'}'", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "FUN_KEYWORD", "MEANINGFUL_TYPE", "VOID", "COMMA", "OBRACE", "CBRACE", 
		"OBRACKET", "CBRACKET", "WS", "INT", "WORD", "DOUBLE", "CALL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Ninja.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static NinjaLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\xF', 'n', '\b', '\x1', '\x4', '\x2', '\t', '\x2', '\x4', 
		'\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', 
		'\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', 
		'\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', 
		'\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x5', 
		'\x3', '\x31', '\n', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\n', '\x6', '\n', '\x43', '\n', '\n', '\r', 
		'\n', '\xE', '\n', '\x44', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x5', 
		'\v', 'J', '\n', '\v', '\x3', '\v', '\x6', '\v', 'M', '\n', '\v', '\r', 
		'\v', '\xE', '\v', 'N', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x6', 
		'\r', 'T', '\n', '\r', '\r', '\r', '\xE', '\r', 'U', '\x3', '\xE', '\x5', 
		'\xE', 'Y', '\n', '\xE', '\x3', '\xE', '\a', '\xE', '\\', '\n', '\xE', 
		'\f', '\xE', '\xE', '\xE', '_', '\v', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x6', '\xE', '\x63', '\n', '\xE', '\r', '\xE', '\xE', '\xE', '\x64', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', '\xF', 
		'k', '\n', '\xF', '\x3', '\xF', '\x3', '\xF', '\x2', '\x2', '\x10', '\x3', 
		'\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', 
		'\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\x2', 
		'\x19', '\r', '\x1B', '\xE', '\x1D', '\xF', '\x3', '\x2', '\t', '\x5', 
		'\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x4', '\x2', '-', '-', '/', 
		'/', '\x3', '\x2', '\x32', ';', '\x4', '\x2', '\x43', '\\', '\x63', '|', 
		'\x3', '\x2', '\x30', '\x30', '\x3', '\x2', '*', '*', '\x3', '\x2', '+', 
		'+', '\x2', 'v', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x3', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '\x30', '\x3', '\x2', '\x2', '\x2', '\a', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\t', '\x37', '\x3', '\x2', '\x2', 
		'\x2', '\v', '\x39', '\x3', '\x2', '\x2', '\x2', '\r', ';', '\x3', '\x2', 
		'\x2', '\x2', '\xF', '=', '\x3', '\x2', '\x2', '\x2', '\x11', '?', '\x3', 
		'\x2', '\x2', '\x2', '\x13', '\x42', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'I', '\x3', '\x2', '\x2', '\x2', '\x17', 'P', '\x3', '\x2', '\x2', '\x2', 
		'\x19', 'S', '\x3', '\x2', '\x2', '\x2', '\x1B', 'X', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\x66', '\x3', '\x2', '\x2', '\x2', '\x1F', ' ', '\a', 
		'h', '\x2', '\x2', ' ', '!', '\a', 'w', '\x2', '\x2', '!', '\"', '\a', 
		'p', '\x2', '\x2', '\"', '\x4', '\x3', '\x2', '\x2', '\x2', '#', '$', 
		'\a', 'k', '\x2', '\x2', '$', '%', '\a', 'p', '\x2', '\x2', '%', '\x31', 
		'\a', 'v', '\x2', '\x2', '&', '\'', '\a', '\x66', '\x2', '\x2', '\'', 
		'(', '\a', 'q', '\x2', '\x2', '(', ')', '\a', 'w', '\x2', '\x2', ')', 
		'*', '\a', '\x64', '\x2', '\x2', '*', '+', '\a', 'n', '\x2', '\x2', '+', 
		'\x31', '\a', 'g', '\x2', '\x2', ',', '-', '\a', '\x64', '\x2', '\x2', 
		'-', '.', '\a', 'q', '\x2', '\x2', '.', '/', '\a', 'q', '\x2', '\x2', 
		'/', '\x31', '\a', 'n', '\x2', '\x2', '\x30', '#', '\x3', '\x2', '\x2', 
		'\x2', '\x30', '&', '\x3', '\x2', '\x2', '\x2', '\x30', ',', '\x3', '\x2', 
		'\x2', '\x2', '\x31', '\x6', '\x3', '\x2', '\x2', '\x2', '\x32', '\x33', 
		'\a', 'x', '\x2', '\x2', '\x33', '\x34', '\a', 'q', '\x2', '\x2', '\x34', 
		'\x35', '\a', 'k', '\x2', '\x2', '\x35', '\x36', '\a', '\x66', '\x2', 
		'\x2', '\x36', '\b', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\a', 
		'.', '\x2', '\x2', '\x38', '\n', '\x3', '\x2', '\x2', '\x2', '\x39', ':', 
		'\a', '}', '\x2', '\x2', ':', '\f', '\x3', '\x2', '\x2', '\x2', ';', '<', 
		'\a', '\x7F', '\x2', '\x2', '<', '\xE', '\x3', '\x2', '\x2', '\x2', '=', 
		'>', '\a', '*', '\x2', '\x2', '>', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'?', '@', '\a', '+', '\x2', '\x2', '@', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'\x41', '\x43', '\t', '\x2', '\x2', '\x2', '\x42', '\x41', '\x3', '\x2', 
		'\x2', '\x2', '\x43', '\x44', '\x3', '\x2', '\x2', '\x2', '\x44', '\x42', 
		'\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\x3', '\x2', '\x2', '\x2', 
		'\x45', '\x46', '\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\b', '\n', '\x2', 
		'\x2', 'G', '\x14', '\x3', '\x2', '\x2', '\x2', 'H', 'J', '\t', '\x3', 
		'\x2', '\x2', 'I', 'H', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\x3', '\x2', 
		'\x2', '\x2', 'J', 'L', '\x3', '\x2', '\x2', '\x2', 'K', 'M', '\x5', '\x17', 
		'\f', '\x2', 'L', 'K', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\x3', '\x2', 
		'\x2', '\x2', 'N', 'L', '\x3', '\x2', '\x2', '\x2', 'N', 'O', '\x3', '\x2', 
		'\x2', '\x2', 'O', '\x16', '\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\t', 
		'\x4', '\x2', '\x2', 'Q', '\x18', '\x3', '\x2', '\x2', '\x2', 'R', 'T', 
		'\t', '\x5', '\x2', '\x2', 'S', 'R', '\x3', '\x2', '\x2', '\x2', 'T', 
		'U', '\x3', '\x2', '\x2', '\x2', 'U', 'S', '\x3', '\x2', '\x2', '\x2', 
		'U', 'V', '\x3', '\x2', '\x2', '\x2', 'V', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'Y', '\t', '\x3', '\x2', '\x2', 'X', 'W', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'Y', '\x3', '\x2', '\x2', '\x2', 'Y', ']', '\x3', '\x2', '\x2', 
		'\x2', 'Z', '\\', '\x5', '\x17', '\f', '\x2', '[', 'Z', '\x3', '\x2', 
		'\x2', '\x2', '\\', '_', '\x3', '\x2', '\x2', '\x2', ']', '[', '\x3', 
		'\x2', '\x2', '\x2', ']', '^', '\x3', '\x2', '\x2', '\x2', '^', '`', '\x3', 
		'\x2', '\x2', '\x2', '_', ']', '\x3', '\x2', '\x2', '\x2', '`', '\x62', 
		'\t', '\x6', '\x2', '\x2', '\x61', '\x63', '\x5', '\x17', '\f', '\x2', 
		'\x62', '\x61', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\x3', '\x2', 
		'\x2', '\x2', '\x64', '\x62', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', 
		'\x3', '\x2', '\x2', '\x2', '\x65', '\x1C', '\x3', '\x2', '\x2', '\x2', 
		'\x66', 'g', '\x5', '\x19', '\r', '\x2', 'g', 'j', '\t', '\a', '\x2', 
		'\x2', 'h', 'k', '\x5', '\x15', '\v', '\x2', 'i', 'k', '\x5', '\x1B', 
		'\xE', '\x2', 'j', 'h', '\x3', '\x2', '\x2', '\x2', 'j', 'i', '\x3', '\x2', 
		'\x2', '\x2', 'k', 'l', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\t', '\b', 
		'\x2', '\x2', 'm', '\x1E', '\x3', '\x2', '\x2', '\x2', '\f', '\x2', '\x30', 
		'\x44', 'I', 'N', 'U', 'X', ']', '\x64', 'j', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
