//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ..\..\..\Interpreter\Ninja.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="INinjaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class NinjaBaseListener : INinjaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] NinjaParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] NinjaParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMain([NotNull] NinjaParser.MainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMain([NotNull] NinjaParser.MainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.main_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMain_signature([NotNull] NinjaParser.Main_signatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.main_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMain_signature([NotNull] NinjaParser.Main_signatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] NinjaParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] NinjaParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.v_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterV_function([NotNull] NinjaParser.V_functionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.v_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitV_function([NotNull] NinjaParser.V_functionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.v_fun_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterV_fun_signature([NotNull] NinjaParser.V_fun_signatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.v_fun_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitV_fun_signature([NotNull] NinjaParser.V_fun_signatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.m_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterM_function([NotNull] NinjaParser.M_functionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.m_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitM_function([NotNull] NinjaParser.M_functionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.m_fun_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterM_fun_signature([NotNull] NinjaParser.M_fun_signatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.m_fun_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitM_fun_signature([NotNull] NinjaParser.M_fun_signatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode([NotNull] NinjaParser.CodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode([NotNull] NinjaParser.CodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.main_code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMain_code([NotNull] NinjaParser.Main_codeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.main_code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMain_code([NotNull] NinjaParser.Main_codeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.method_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod_return([NotNull] NinjaParser.Method_returnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.method_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod_return([NotNull] NinjaParser.Method_returnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParams([NotNull] NinjaParser.ParamsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParams([NotNull] NinjaParser.ParamsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.var_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_signature([NotNull] NinjaParser.Var_signatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.var_signature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_signature([NotNull] NinjaParser.Var_signatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.builtin_func_p"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuiltin_func_p([NotNull] NinjaParser.Builtin_func_pContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.builtin_func_p"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuiltin_func_p([NotNull] NinjaParser.Builtin_func_pContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.builtin_func_e"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBuiltin_func_e([NotNull] NinjaParser.Builtin_func_eContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.builtin_func_e"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBuiltin_func_e([NotNull] NinjaParser.Builtin_func_eContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall([NotNull] NinjaParser.CallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall([NotNull] NinjaParser.CallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.parameterized_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterized_call([NotNull] NinjaParser.Parameterized_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.parameterized_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterized_call([NotNull] NinjaParser.Parameterized_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.simple_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_call([NotNull] NinjaParser.Simple_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.simple_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_call([NotNull] NinjaParser.Simple_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.custom_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCustom_call([NotNull] NinjaParser.Custom_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.custom_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCustom_call([NotNull] NinjaParser.Custom_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.call_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall_params([NotNull] NinjaParser.Call_paramsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.call_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall_params([NotNull] NinjaParser.Call_paramsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="NinjaParser.call_param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall_param([NotNull] NinjaParser.Call_paramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="NinjaParser.call_param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall_param([NotNull] NinjaParser.Call_paramContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
