//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ..\..\..\Interpreter\Ninja.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class NinjaLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, RETURN_KEYWORD=5, MAIN=6, FUN_KEYWORD=7, 
		MEANINGFUL_TYPE=8, VOID=9, COMMA=10, OBRACE=11, CBRACE=12, OBRACKET=13, 
		CBRACKET=14, WS=15, COMMENT=16, BOOL=17, DOUBLE=18, INT=19, WORD=20, STRING=21;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "RETURN_KEYWORD", "MAIN", "FUN_KEYWORD", 
		"MEANINGFUL_TYPE", "VOID", "COMMA", "OBRACE", "CBRACE", "OBRACKET", "CBRACKET", 
		"WS", "COMMENT", "BOOL", "DOUBLE", "INT", "DIGIT", "WORD", "STRING"
	};


	public NinjaLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public NinjaLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'move'", "'turn'", "'hit'", "'shoot'", "'return'", "'main'", "'fun'", 
		null, "'void'", "','", "'{'", "'}'", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "RETURN_KEYWORD", "MAIN", "FUN_KEYWORD", 
		"MEANINGFUL_TYPE", "VOID", "COMMA", "OBRACE", "CBRACE", "OBRACKET", "CBRACKET", 
		"WS", "COMMENT", "BOOL", "DOUBLE", "INT", "WORD", "STRING"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Ninja.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static NinjaLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x17', '\xB7', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x5', '\t', '\x61', '\n', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\x10', '\x6', '\x10', 's', '\n', '\x10', 
		'\r', '\x10', '\xE', '\x10', 't', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\a', '\x11', '}', 
		'\n', '\x11', '\f', '\x11', '\xE', '\x11', '\x80', '\v', '\x11', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', '\x8F', '\n', '\x12', 
		'\x3', '\x13', '\x5', '\x13', '\x92', '\n', '\x13', '\x3', '\x13', '\a', 
		'\x13', '\x95', '\n', '\x13', '\f', '\x13', '\xE', '\x13', '\x98', '\v', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x6', '\x13', '\x9C', '\n', '\x13', 
		'\r', '\x13', '\xE', '\x13', '\x9D', '\x3', '\x14', '\x5', '\x14', '\xA1', 
		'\n', '\x14', '\x3', '\x14', '\x6', '\x14', '\xA4', '\n', '\x14', '\r', 
		'\x14', '\xE', '\x14', '\xA5', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', 
		'\x6', '\x16', '\xAB', '\n', '\x16', '\r', '\x16', '\xE', '\x16', '\xAC', 
		'\x3', '\x17', '\x3', '\x17', '\a', '\x17', '\xB1', '\n', '\x17', '\f', 
		'\x17', '\xE', '\x17', '\xB4', '\v', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '~', '\x2', '\x18', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', 
		'\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', 
		'\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', 
		'\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', ')', 
		'\x2', '+', '\x16', '-', '\x17', '\x3', '\x2', '\b', '\x5', '\x2', '\v', 
		'\f', '\xF', '\xF', '\"', '\"', '\x3', '\x2', '\f', '\f', '\x4', '\x2', 
		'-', '-', '/', '/', '\x3', '\x2', '\x30', '\x30', '\x3', '\x2', '\x32', 
		';', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x2', '\xC1', '\x2', '\x3', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x3', '/', 
		'\x3', '\x2', '\x2', '\x2', '\x5', '\x34', '\x3', '\x2', '\x2', '\x2', 
		'\a', '\x39', '\x3', '\x2', '\x2', '\x2', '\t', '=', '\x3', '\x2', '\x2', 
		'\x2', '\v', '\x43', '\x3', '\x2', '\x2', '\x2', '\r', 'J', '\x3', '\x2', 
		'\x2', '\x2', '\xF', 'O', '\x3', '\x2', '\x2', '\x2', '\x11', '`', '\x3', 
		'\x2', '\x2', '\x2', '\x13', '\x62', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'g', '\x3', '\x2', '\x2', '\x2', '\x17', 'i', '\x3', '\x2', '\x2', '\x2', 
		'\x19', 'k', '\x3', '\x2', '\x2', '\x2', '\x1B', 'm', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', 'o', '\x3', '\x2', '\x2', '\x2', '\x1F', 'r', '\x3', '\x2', 
		'\x2', '\x2', '!', 'x', '\x3', '\x2', '\x2', '\x2', '#', '\x8E', '\x3', 
		'\x2', '\x2', '\x2', '%', '\x91', '\x3', '\x2', '\x2', '\x2', '\'', '\xA0', 
		'\x3', '\x2', '\x2', '\x2', ')', '\xA7', '\x3', '\x2', '\x2', '\x2', '+', 
		'\xAA', '\x3', '\x2', '\x2', '\x2', '-', '\xAE', '\x3', '\x2', '\x2', 
		'\x2', '/', '\x30', '\a', 'o', '\x2', '\x2', '\x30', '\x31', '\a', 'q', 
		'\x2', '\x2', '\x31', '\x32', '\a', 'x', '\x2', '\x2', '\x32', '\x33', 
		'\a', 'g', '\x2', '\x2', '\x33', '\x4', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x35', '\a', 'v', '\x2', '\x2', '\x35', '\x36', '\a', 'w', '\x2', '\x2', 
		'\x36', '\x37', '\a', 't', '\x2', '\x2', '\x37', '\x38', '\a', 'p', '\x2', 
		'\x2', '\x38', '\x6', '\x3', '\x2', '\x2', '\x2', '\x39', ':', '\a', 'j', 
		'\x2', '\x2', ':', ';', '\a', 'k', '\x2', '\x2', ';', '<', '\a', 'v', 
		'\x2', '\x2', '<', '\b', '\x3', '\x2', '\x2', '\x2', '=', '>', '\a', 'u', 
		'\x2', '\x2', '>', '?', '\a', 'j', '\x2', '\x2', '?', '@', '\a', 'q', 
		'\x2', '\x2', '@', '\x41', '\a', 'q', '\x2', '\x2', '\x41', '\x42', '\a', 
		'v', '\x2', '\x2', '\x42', '\n', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', 
		'\a', 't', '\x2', '\x2', '\x44', '\x45', '\a', 'g', '\x2', '\x2', '\x45', 
		'\x46', '\a', 'v', '\x2', '\x2', '\x46', 'G', '\a', 'w', '\x2', '\x2', 
		'G', 'H', '\a', 't', '\x2', '\x2', 'H', 'I', '\a', 'p', '\x2', '\x2', 
		'I', '\f', '\x3', '\x2', '\x2', '\x2', 'J', 'K', '\a', 'o', '\x2', '\x2', 
		'K', 'L', '\a', '\x63', '\x2', '\x2', 'L', 'M', '\a', 'k', '\x2', '\x2', 
		'M', 'N', '\a', 'p', '\x2', '\x2', 'N', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'O', 'P', '\a', 'h', '\x2', '\x2', 'P', 'Q', '\a', 'w', '\x2', '\x2', 
		'Q', 'R', '\a', 'p', '\x2', '\x2', 'R', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'S', 'T', '\a', 'k', '\x2', '\x2', 'T', 'U', '\a', 'p', '\x2', '\x2', 
		'U', '\x61', '\a', 'v', '\x2', '\x2', 'V', 'W', '\a', '\x66', '\x2', '\x2', 
		'W', 'X', '\a', 'q', '\x2', '\x2', 'X', 'Y', '\a', 'w', '\x2', '\x2', 
		'Y', 'Z', '\a', '\x64', '\x2', '\x2', 'Z', '[', '\a', 'n', '\x2', '\x2', 
		'[', '\x61', '\a', 'g', '\x2', '\x2', '\\', ']', '\a', '\x64', '\x2', 
		'\x2', ']', '^', '\a', 'q', '\x2', '\x2', '^', '_', '\a', 'q', '\x2', 
		'\x2', '_', '\x61', '\a', 'n', '\x2', '\x2', '`', 'S', '\x3', '\x2', '\x2', 
		'\x2', '`', 'V', '\x3', '\x2', '\x2', '\x2', '`', '\\', '\x3', '\x2', 
		'\x2', '\x2', '\x61', '\x12', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', 
		'\a', 'x', '\x2', '\x2', '\x63', '\x64', '\a', 'q', '\x2', '\x2', '\x64', 
		'\x65', '\a', 'k', '\x2', '\x2', '\x65', '\x66', '\a', '\x66', '\x2', 
		'\x2', '\x66', '\x14', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', '.', 
		'\x2', '\x2', 'h', '\x16', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', 
		'}', '\x2', '\x2', 'j', '\x18', '\x3', '\x2', '\x2', '\x2', 'k', 'l', 
		'\a', '\x7F', '\x2', '\x2', 'l', '\x1A', '\x3', '\x2', '\x2', '\x2', 'm', 
		'n', '\a', '*', '\x2', '\x2', 'n', '\x1C', '\x3', '\x2', '\x2', '\x2', 
		'o', 'p', '\a', '+', '\x2', '\x2', 'p', '\x1E', '\x3', '\x2', '\x2', '\x2', 
		'q', 's', '\t', '\x2', '\x2', '\x2', 'r', 'q', '\x3', '\x2', '\x2', '\x2', 
		's', 't', '\x3', '\x2', '\x2', '\x2', 't', 'r', '\x3', '\x2', '\x2', '\x2', 
		't', 'u', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\x3', '\x2', '\x2', '\x2', 
		'v', 'w', '\b', '\x10', '\x2', '\x2', 'w', ' ', '\x3', '\x2', '\x2', '\x2', 
		'x', 'y', '\a', '\x31', '\x2', '\x2', 'y', 'z', '\a', '\x31', '\x2', '\x2', 
		'z', '~', '\x3', '\x2', '\x2', '\x2', '{', '}', '\v', '\x2', '\x2', '\x2', 
		'|', '{', '\x3', '\x2', '\x2', '\x2', '}', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '~', '\x7F', '\x3', '\x2', '\x2', '\x2', '~', '|', '\x3', '\x2', 
		'\x2', '\x2', '\x7F', '\x81', '\x3', '\x2', '\x2', '\x2', '\x80', '~', 
		'\x3', '\x2', '\x2', '\x2', '\x81', '\x82', '\t', '\x3', '\x2', '\x2', 
		'\x82', '\x83', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\b', '\x11', 
		'\x2', '\x2', '\x84', '\"', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', 
		'\a', 'v', '\x2', '\x2', '\x86', '\x87', '\a', 't', '\x2', '\x2', '\x87', 
		'\x88', '\a', 'w', '\x2', '\x2', '\x88', '\x8F', '\a', 'g', '\x2', '\x2', 
		'\x89', '\x8A', '\a', 'h', '\x2', '\x2', '\x8A', '\x8B', '\a', '\x63', 
		'\x2', '\x2', '\x8B', '\x8C', '\a', 'n', '\x2', '\x2', '\x8C', '\x8D', 
		'\a', 'u', '\x2', '\x2', '\x8D', '\x8F', '\a', 'g', '\x2', '\x2', '\x8E', 
		'\x85', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x89', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '$', '\x3', '\x2', '\x2', '\x2', '\x90', '\x92', '\t', 
		'\x4', '\x2', '\x2', '\x91', '\x90', '\x3', '\x2', '\x2', '\x2', '\x91', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '\x92', '\x96', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x95', '\x5', ')', '\x15', '\x2', '\x94', '\x93', '\x3', 
		'\x2', '\x2', '\x2', '\x95', '\x98', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x94', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\x3', '\x2', '\x2', 
		'\x2', '\x97', '\x99', '\x3', '\x2', '\x2', '\x2', '\x98', '\x96', '\x3', 
		'\x2', '\x2', '\x2', '\x99', '\x9B', '\t', '\x5', '\x2', '\x2', '\x9A', 
		'\x9C', '\x5', ')', '\x15', '\x2', '\x9B', '\x9A', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9D', '\x9E', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'&', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA1', '\t', '\x4', '\x2', '\x2', 
		'\xA0', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\x3', '\x2', 
		'\x2', '\x2', '\xA1', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA4', 
		'\x5', ')', '\x15', '\x2', '\xA3', '\xA2', '\x3', '\x2', '\x2', '\x2', 
		'\xA4', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA3', '\x3', '\x2', 
		'\x2', '\x2', '\xA5', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA6', '(', 
		'\x3', '\x2', '\x2', '\x2', '\xA7', '\xA8', '\t', '\x6', '\x2', '\x2', 
		'\xA8', '*', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAB', '\t', '\a', '\x2', 
		'\x2', '\xAA', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xAD', '\x3', '\x2', '\x2', '\x2', '\xAD', ',', '\x3', '\x2', '\x2', 
		'\x2', '\xAE', '\xB2', '\a', '$', '\x2', '\x2', '\xAF', '\xB1', '\t', 
		'\a', '\x2', '\x2', '\xB0', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xB1', 
		'\xB4', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB0', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB5', '\x3', 
		'\x2', '\x2', '\x2', '\xB4', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB5', 
		'\xB6', '\a', '$', '\x2', '\x2', '\xB6', '.', '\x3', '\x2', '\x2', '\x2', 
		'\xE', '\x2', '`', 't', '~', '\x8E', '\x91', '\x96', '\x9D', '\xA0', '\xA5', 
		'\xAC', '\xB2', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
